#!/usr/bin/env ruby
require 'rubygems'
require 'fileutils'
require 'orpium'
require 'term/ansicolor'
require 'restclient'

class String
  include Term::ANSIColor
end

config = YAML.load_file 'profiles/default.yml'

FileUtils.mkdir_p 'build/srpms'
FileUtils.mkdir_p 'build/rpms'
FileUtils.mkdir_p 'build/repos'
FileUtils.mkdir_p 'build/repos-ee'

# Clean ~/rpmbuild
rpmbuild_dir = "#{ENV['HOME']}/rpmbuild"
%w(SRPMS SPECS SOURCES BUILD BUILDROOT RPMS).each do |d|
  dir = File.join(topdir, d)
  FileUtils.rm_rf dir
  Dir.mkdir dir
end

# Clean old SRPMS
Dir["build/srpms/*.rpm"].each do |f|
  FileUtils.rm_f f
end

# Clean old RPMS
Dir["build/rpms/*.rpm"].each do |f|
  FileUtils.rm_f f
end

if config[:run_steps][:clone_common_repos]
  puts
  puts "Clone/Update common repos".bold
  puts
  require 'lib/clone-common-repos'
end

if config[:run_steps][:clone_private_repos]
  puts
  puts "Clone/Update private repos".bold
  puts
  require 'lib/clone-private-repos'
end

if config[:run_steps][:update_platform_sources]
  puts
  puts "Updating platform sources".bold
  puts
  require 'lib/update-platform-sources'
end

if config[:run_steps][:create_srpms]
  puts
  puts "Create SRPMS".bold
  puts
  require 'lib/create-srpms'
end

if config[:run_steps][:build_rpms]
  puts
  puts "Build RPMS".bold
  puts
  require 'lib/build-rpms'
end
